backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/images'
public_folder: '/_astro'

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/data/post'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: true }
      - { label: 'Author', name: 'author', widget: 'string', required: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - label: 'Metadata'
        name: 'metadata'
        widget: 'object'
        required: false
        fields:
          - { label: 'Canonical', name: 'canonical', widget: 'string', required: false }
      - { label: 'Content', name: 'body', widget: 'markdown' }
